export { default as Navigation } from "./navbar";
export { default as Footer } from "./footer";
export { default as Home } from "./home";
export { default as SignUp } from "./Authentication/signup";
export { default as SignIn } from "./Authentication/signin";
export { default as Forgot } from "./Authentication/forgot";
export { default as ResetPassword } from "./Authentication/reset";
export { default as About } from "./about";
export { default as Contact } from "./contact";